spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/spring?useSSL=false
  data:
    redis:
      host: 192.168.147.128
      port: 6379
      lettuce:
        pool:
          max-wait: 1000
          max-active: 8
          max-idle: 8
          min-idle: 0
      password: 123456

mybatis:
  mapper-locations: classpath:/*.xml

